mysite/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name="detail") 
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

from rest_framework import routers
from api2.views import TodoViewSet

router = routers.DefaultRouter()
router.register(r'todos', TodoViewSet)

movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include("movies.urls")),
    path('api/', include(movie_resource.urls)),
    # path('api2/', include("api2.urls")),
    path('todos/', include(router.urls)),

]

mysite/api/models.py
from tastypie.resources import ModelResource
from tastypie import fields
from movies.models import Movie, Genre


class GenreResource(ModelResource):
    class Meta:
        queryset = Genre.objects.all()
        resource_name = 'genres'


class MovieResource(ModelResource):
    genre = fields.ForeignKey(GenreResource, 'genre', full=True)

    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'

    def determine_format(self, request):
        fmt = super(MovieResource, self).determine_format(request)

        if fmt == 'text/html':
            return 'application/json'

        return fmt

    def dispatch(self, request_type, request, **kwargs):
        # Allow DELETE requests sent from forms
        if request_type == 'DELETE' and 'HTTP_X_METHODOVERRIDE' in request.META:
            request_type = 'DELETE'

        return super(MovieResource, self).dispatch(request_type, request, **kwargs)

mysite/api2/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    
    def __str__(self):
        return self.title

mysite/movies/models.py
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

# new , change the display of the data in the administration
    def __str__(self):
        return self.name


class Movie(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

mysite/api/views.py
from django.shortcuts import render

# Create your views here.

mysite/api2/views.py
from rest_framework import viewsets
from .models import Todo
from .serializers import TodoSerializer


class TodoViewSet(viewsets.ModelViewSet):
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer

mysite/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

# Create your views here.
# def index(request):
#     return HttpResponse("Hello word")

def index(request):
    movies = Movie.objects.all()
    # output = ', '.join([m.name for m in movies])
        # return render(request, 'index.html', {'movies': movies})
    # return HttpResponse("Hello word")
    # return HttpResponse(output)
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):

    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'movies/detail.html', {'movie': movie})

mysite/mysite/views.py
from django.shortcuts import render


def home(request):
    # print 'jeffrey'
    return render(request, 'home.html')

mysite/movies/templates/index.html
{% extends 'base.html' %}

{% block content %}
    {% comment %} table.table>thead>tr>th*3 {% endcomment %}
            
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <!-- tbody>tr>td*4 -->
        <tbody>
            {% for movie in movies %}
            
            <tr>
                <td>
                    <a href="{% url 'movies:detail' movie.id%}">{{ movie.name }}</a>
                    </td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rate }}</td> 
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

mysite/movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
    <!-- dl>(dt+dd)*3 -->
    <dl>
        <dt>Name</dt>
        <dd>{{ movie.name}}</dd>
        <dt>Genre</dt>
        <dd>{{movie.genre}}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stock}}</dd>
    </dl>
{% endblock  %} 

mysite/movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %} 
            
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie in movies %}
            
            <tr>
                <td>
                    <a href="{% url 'movies:detail' movie.id%}">{{ movie.name }}</a>
                    {% comment %} <a href="/movies/{{ movie.id }}"> {{ movie.name }}</a> {% endcomment %}
                    {% comment %} {{ movie.name }} {% endcomment %}
                    </td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rate }}</td> 
            </tr>
            {% endfor %}
        </tbody> 
    </table>
{% endblock %}

mysite/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>VidlyPython2</title>
  </head>
  <body>

        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
            <a class="navbar-brand" href="#">VidlyPython2</a>
            </div>
        </nav>
        
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">            
              <span class="navbar-brand mb-0 h1">Navbar</span>
            </div>
        </nav>


    <main class="container">
        
    {% block content %}
    {% endblock %} 
    
    <main/>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}